import { useNavigate } from "react-router-dom";
import { slugify } from "@shared/format";
import { useDataset } from "../../hooks/useDataset";
import { Section } from "../../components/common/Section";
import type { InsightCard } from "@shared/types";

const SECTIONS: Array<{ key: InsightCard["section"]; title: string; blurb: string }> = [
  { key: "STRONGEST", title: "Strongest topics", blurb: "Highest average views in the current window." },
  { key: "WEAKEST", title: "Weakest topics", blurb: "Topics pulling below the account floor." },
  { key: "BREAKOUT", title: "Breakout patterns", blurb: "Outlier Reels and the topics they belong to." },
  { key: "UNDERPERFORMING", title: "Underperforming patterns", blurb: "Repeated below-benchmark posts." },
  { key: "OPPORTUNITY", title: "Content opportunities", blurb: "Quadrant recommendations derived from reach × engagement." },
  { key: "FORMAT", title: "Format opportunities", blurb: "Content types that currently convert reach most efficiently." },
];

export function InsightsPage() {
  const { analytics } = useDataset();
  const navigate = useNavigate();

  return (
    <div>
      <div className="border-b border-[var(--border)] bg-[var(--surface-0)] px-4 py-3">
        <div className="label-caps text-[var(--primary)]">Decision layer</div>
        <h1 className="text-2xl font-semibold uppercase">Insights</h1>
        <p className="text-sm text-[var(--text-2)]">What should we do next? Each card is computed from the analytics engine — not generated by a chatbot.</p>
      </div>
      {SECTIONS.map((section) => {
        const cards = analytics.insights.filter((card) => card.section === section.key);
        return (
          <Section key={section.key} title={section.title} explanation={section.blurb}>
            {cards.length === 0 ? <p className="text-sm text-[var(--text-3)]">No signal in the current filter window.</p> : null}
            <div className="grid grid-cols-1 gap-3 lg:grid-cols-2">
              {cards.map((card) => (
                <article key={card.id} className="border border-[var(--border)] bg-[var(--surface-2)] p-4">
                  <h3 className="text-lg font-semibold uppercase">{card.title}</h3>
                  <div className="mt-3 space-y-2 text-sm">
                    <p><span className="label-caps text-[var(--text-3)]">Observation</span><br />{card.observation}</p>
                    <p><span className="label-caps text-[var(--text-3)]">Data</span><br />{card.data}</p>
                    <p><span className="label-caps text-[var(--text-3)]">Comparison</span><br />{card.comparison}</p>
                    <p><span className="label-caps text-[var(--text-3)]">Action</span><br />{card.action}</p>
                  </div>
                  {card.topic ? (
                    <button
                      type="button"
                      className="label-caps mt-3 bg-[var(--primary-strong)] px-3 py-1 text-[var(--on-primary)]"
                      onClick={() => navigate(`/topics/${slugify(card.topic!)}`)}
                    >
                      Open topic
                    </button>
                  ) : null}
                </article>
              ))}
            </div>
          </Section>
        );
      })}
    </div>
  );
}
